# -*- coding: utf-8 -*-
"""automate_Muhammad Resa Oktavianto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAeoMOFdgRS0AlDaQxJGq3zQQDBgOr7k

# **1. Perkenalan Dataset**

Sumber Data set dari kaggle: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset

# **2. Import Library**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

"""# **3. Memuat Dataset**"""

df = pd.read_csv('healthcare-dataset-stroke-data_raw/healthcare-dataset-stroke-data.csv')

df.head()

"""# **4. Exploratory Data Analysis (EDA)**


"""

df.info()

df.isnull().sum()

df.sort_values('age', ascending=False).head()

plt.style.use('ggplot')
plt.figure(figsize=(12,6))
sns.countplot(x=df['gender'])
plt.title("JUMLAH PASIEN BERDASARKAN GENDER", fontsize=20, fontweight='bold')
plt.show()

"""# **5. Data Preprocessing**"""

df['bmi'] = df['bmi'].fillna(df['bmi'].median())

categorical_cols = ['gender', 'ever_married', 'Residence_type',
                    'work_type', 'smoking_status']

categorical_cols = [col for col in categorical_cols if col in df.columns]

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df = df.astype(int)

df = df.drop(columns=['id'])

df.head()
